  Counter-App[m
  angilar-cli[m
  cllick-event[m
  components[m
  custom[m
  data-type[m
  else-if[m
  event-binding[m
  for-contextual-variable[m
  function-call[m
  if-else[m
  input-field-methods[m
  interpolation[m
  loops[m
  main[m
  property-binding[m
* [32msignal-with-datatypes[m
  signals[m
  styling[m
  switch[m
